// Builds the app's data from data/ and the single-file copy of the app.
// Run after editing anything in data/ or app/:  node tools/build.mjs
//   app/data.js                      generated from data/*.csv and data/decision-rules.json
//   app/shredded-system-single.html  the whole app in one file (open it anywhere, no server needed)
import fs from 'node:fs';
import { csv, templates } from './macros.mjs';

const root = new URL('../', import.meta.url);
const read = (p) => fs.readFileSync(new URL(p, root), 'utf8');
const write = (p, s) => fs.writeFileSync(new URL(p, root), s);

const num = (v) => (v === '' ? null : Number(v));
const foods = csv('foods.csv').map((f) => ({
  id: f.id, name: f.name, kcal: num(f.kcal), p: num(f.protein_g), f: num(f.fat_g), c: num(f.carbs_g), fib: num(f.fibre_g), sat: num(f.satfat_g),
  unitG: num(f.unit_g), unit: f.unit || '', note: f.notes || '',
}));
const { templates: ts } = templates();
const tpl = Object.values(ts).map((t) => ({ id: t.id, name: t.name, type: t.day_type, meals: t.meals.map((m) => ({ n: m.n, name: m.name, items: m.items })) }));
const wk = {};
for (const r of csv('workout-templates.csv')) {
  (wk[r.template_id] ||= { id: r.template_id, name: r.template_name, ex: [] }).ex.push({ name: r.exercise, sets: Number(r.sets), lo: Number(r.rep_low), hi: Number(r.rep_high), rir: r.target_rir, note: r.notes || '' });
}
const rules = JSON.parse(read('data/decision-rules.json'));

const data = `'use strict';
/* GENERATED by tools/build.mjs from data/. Edit the CSV and JSON files there, then rebuild. */
const FOODS = ${JSON.stringify(foods)};
const TEMPLATES = ${JSON.stringify(tpl)};
const WORKOUTS = ${JSON.stringify(Object.values(wk))};
const RULES = ${JSON.stringify(rules)};
`;
write('app/data.js', data);

// Single-file copy: the whole app in one page.
const html = read('app/index.html');
// Every local <script src="x.js"> is inlined (data.js from memory, the rest from app/).
const single = html
  .replace(/<script src="([a-z0-9-]+\.js)"><\/script>/g, (_, f) => `<script>\n${f === 'data.js' ? data : read(`app/${f}`)}</script>`)
  .replace(/<link rel="manifest"[^>]*>\n?/, '');
write('app/shredded-system-single.html', single);

// An embeddable fragment (no html/head/body wrapper) for hosts that add their own, such as a claude.ai artifact.
if (process.argv[2]) {
  const frag = single
    .replace(/<!doctype html>\s*/i, '')
    .replace(/<html[^>]*>\s*/i, '').replace(/<\/html>\s*/i, '')
    .replace(/<head>\s*/i, '').replace(/<\/head>\s*/i, '')
    .replace(/<body>\s*/i, '').replace(/<\/body>\s*/i, '')
    .replace(/<meta charset[^>]*>\s*/i, '').replace(/<meta name="viewport"[^>]*>\s*/i, '')
    .replace(/<link rel="(icon|apple-touch-icon)"[^>]*>\s*/g, '');
  fs.writeFileSync(process.argv[2], frag);
}
console.log(`data.js: ${foods.length} foods, ${tpl.length} day templates, ${Object.keys(wk).length} workouts, ${rules.rules.length} rules`);
